branches:
  only:
    - master

language: bash

services:
  - docker

#before_install:
#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - repo=gendosu/docker-alpine-base

script:
  - docker build -t $repo .

#after_success:
#  - tag=$(docker run --rm $repo /bin/sh -c 'echo $FAKES3_VERSION')
#  - docker tag $repo $repo:$tag
#  - docker push $repo:latest
#  - docker push $repo:$tag

